### ISSUE TITLE
How to apply to background image & also when the page loads if there is a banner the plugin wont work without scrolling

### ISSUE THREAD

**Issue by suman-george** [craigbuckler/progressive-image.js#1]

**Comment by craigbuckler** [comment]
It won't work with a background image. However, a background will normally be part of your template and reused on many pages - there's less need for it to be progressively loaded.

By "banner" I presume you mean a dynamically-sized image or advert somewhere on the page which pushes the image placeholder into view. You are correct that the image would not load until you scrolled or resized. One way to fix that would be checking every second or so - but it could have a negative impact on performance.

**Comment by suman-george** [comment]
@craigbuckler - Thank you for the reply.
