### ISSUE TITLE
[Question]  Does it support Angular 6 ?

### ISSUE THREAD

**Issue by axacheng** [craigbuckler/progressive-image.js#13]
I've tried many libraries but not yet got lucky.
Not sure this one is compatible with Angular 6 template system to read img from something like {{ image.thumbnail_256_url }} ?

```html
      <div class="view overlay hm-white-slight waves-light" mdbRippleRadius>
        <mdb-carousel [isControls]="true" [interval]=0 class="carousel slide carousel-fade" [type]="'carousel-thumbnails'" [animation]="'fade'">
          <mdb-slide *ngFor="let image of stuff.images">
            <!-- <img class="d-block w-100" src="{{ image.thumbnail_256_url}}" alt=""> -->
            <!-- <img src="{{ image.thumbnail_256_url }}" alt=""> -->
            <img src="{{ image.thumbnail_256_url }}" alt="">
            <div class="carousel-caption" *ngIf="image">
              <h3 class="h3-responsive">{{ image.caption }}</h3>
            </div>
          </mdb-slide>
        </mdb-carousel>
      </div>

```

**Comment by craigbuckler** [comment]
There's nothing about progressive-image.js that would stop it working in any framework. However, most frameworks - including Angular - have their own ways of doing things. So getting it to work is another matter. Best of luck.

You've not included progressive-image.js classes in your code example above so it certainly won't work there.
