### ISSUE TITLE
Not reliably loading images 

### ISSUE THREAD

**Issue by nickcom** [craigbuckler/progressive-image.js#18]
Hi. I love the effect this plugin achieves, but I find that occasionally my site will load but only the blurry placeholder will be displayed - even for those images in the viewport- until I commence a scroll. I’d say this occurs on 5% of page loads while the rest of the time the images visible in the viewport will automatically fade into view without a page scroll being required. How to fix this?

**Comment by craigbuckler** [comment]
Do you have an example page?
Is it consistently failing in those 5% of pages?
Does it happen in all browsers? What browser are you using?

**Comment by craigbuckler** [comment]
Closing. No information.
