### ISSUE TITLE
Image not loaded on modal

### ISSUE THREAD

**Issue by quangvision** [craigbuckler/progressive-image.js#20]
Hello
I am trying to use this with bootstrap modal and image seems not loading on scroll.
Is there anyway to work around this matter?
   Thanks :)

**Comment by craigbuckler** [comment]
Would it be appropriate for a modal? That wouldn't react to a scroll.

I don't really understand the problem. Please publish an example page so I can see what you're trying to achieve.

**Comment by quangvision** [comment]
Pls check this demo.
https://jsfiddle.net/quang_it/b1tufkrq/3/

**Comment by craigbuckler** [comment]
It's not the modal or styles. The JS in your demo is preventing progressive-image.js from running. It's possibly cancelling the `window` load event and there's nothing I can add to prevent that.

If you got it running, you'd possibly have the problem that the window isn't actually scrolled when the modal is active - it's the modal that's scrolled. That could be addressed, though.

**Comment by craigbuckler** [comment]
Closing: fault due to other conflicts.
