### ISSUE TITLE
Images load before scrolling

### ISSUE THREAD

**Issue by sunnmagic** [craigbuckler/progressive-image.js#21]
Hello,

Thanks for this amazing script!

Unfortunately, the images are loading without scrolling, and I don't know why... example: https://www.lumipop.com/391-ampoules-spots-connectes :/

**Comment by craigbuckler** [comment]
The page works for me? Both Chrome and Firefox seem fine?
What browser/version are you using?

**Comment by sunnmagic** [comment]
I'm on Chrome 74.0.3729.169.

If you open Firebug, you will see that all the images in the page are loaded right from the start, even if we don't scroll. Google Page Speed confirm this problem, sending me to this tip : https://developers.google.com/web/tools/lighthouse/audits/offscreen-images

**Comment by craigbuckler** [comment]
The preview images will always load, but they're small?
Are you using the same images for the preview and the full image?

**Comment by sunnmagic** [comment]
Ok I understand, that's because I use the same images for the preview and the full image. My bad, sorry.

Is there a way to lazy load the preview image too? only load it above the fold?

**Comment by craigbuckler** [comment]
That's not really the point of the code! The preview image should be tiny - perhaps 20px width. It loads instantly and shows something while the full image loads (or fails to load).

In your case, you may have hundreds of product images. I'd suggest using the same preview image for each (a 1px grey PNG?) or consider a service such as Cloudinary which can generate tiny resized images by simply changing the URL.

**Comment by sunnmagic** [comment]
I understand, you're right, I will do that, thanks. As it is not an issue, do you want me to remove this topic?

**Comment by craigbuckler** [comment]
Already done, thanks!
