### ISSUE TITLE
Pictures jump  jump

### ISSUE THREAD

**Issue by eteled126** [craigbuckler/progressive-image.js#24]
The space occupied by the thumbnail does not seem to always equal the size of the large image. I always find that the moment when the large image replaces the thumbnail, there is a sense of jumping, which occurs at the bottom of the big picture:
<img src="https://s2.ax1x.com/2019/06/23/ZFCI3D.gif" alt="ZFCI3D.gif" border="0" />
(I recorded a gif, the file is larger)

This situation is even more pronounced when the two figures are close together:
<img src="https://s2.ax1x.com/2019/06/23/ZFiVeA.gif" alt="ZFiVeA.gif" border="0" />

What is the cause of this, how can I solve it? thanks!

Related page http://t.cn/AipxH9T9

**Comment by craigbuckler** [comment]
As mentioned in the README: *both images must have the same aspect ratio.*

If your main image is 800x600, your preview thumbnail could be 20x15, 40x30, 80x60 or any similar multiple.

**This is important!** It's currently the only way to determine the image dimensions (until we get an aspect-ratio HTML or CSS property). You could size the image using `width` and `height` attributes but that won't work if you have a responsive layout.

The layout will jump if you use images with different aspect ratios.
