### ISSUE TITLE
Reveal animation issue in firefox

### ISSUE THREAD

**Issue by SatelierDiego** [craigbuckler/progressive-image.js#32]
Hi.

I`m using this script and everything works fine in Chrome and in IE/Edge. When I tested the site in Firefox, the loaded image "throbs" and never replace the thumb.

The weird thing is that this happens in some images only.

If I disable the animation through the console, the images replaces the thumbnails.

After a while, the replacement works, and the console shows this error:

>  NotFoundError: Node.removeChild: The node to be removed is not a child of this node

How can I fix it?

Thank you.

**Comment by craigbuckler** [comment]
Hi.

This seems slightly weird, but Firefox eventually replaces the images. It just takes time. 

I think there are several things to check.

**1. Don't use `<picture>` as the container**
It's the wrong element and the browser could be attempting weird stuff. Use `<figure>` an `<a>` (as suggested), or even a `<div>`.

**2. Performance could be the problem**
Your page is 50MB and doesn't use compressed assets. It's continually downloading video chunks which hog the bandwidth.

Perhaps disable the video temporarily and see if that makes a difference.

**3. A Cloudflare rocket loader conflict?**
An error being triggered thousands of times...

```
NotFoundError: Node.removeChild: The node to be removed is not a child of this node
    addImg davinci.min.js:5108
    c rocket-loader.min.js:454
```

`addImg` is a progressive-image function and the error could be related to the `<picture>` issue.

However, it's possible the Cloudflare rocket loader is causing a weird conflict. Perhaps disable it temporarily to see if it makes a difference.

I hope that helps.
Please let me know if you find the problem.

**Comment by SatelierDiego** [comment]
Hi Craig, thank you for your help.

I fixed the issue changing the container from `<pinture>` to `<figure>`

Disabling the video don't affect anything.

With the tag change, no error is triggered.

Thank you again for your time and detailed answer.

**Comment by craigbuckler** [comment]
You're welcome.
