### ISSUE TITLE
Provide an example for background-image

### ISSUE THREAD

**Issue by blasco** [craigbuckler/progressive-image.js#37]
I've managed to get it working with a normal image. In the features it is listed that it should work with a background image too. Could an example be added to the readme?

**Comment by craigbuckler** [comment]
I'll add a one (and fix the issue loading the script in the `<head>`).

Note that background images are limited. Animation isn't possible and there may be better alternatives if that's the only thing you want to do.

**Comment by blasco** [comment]
I'm not doing any fancy animation, looking forward to test it out

**Comment by craigbuckler** [comment]
Fixed, but documentation now mostly in `demo.html` and at [Codepen](https://codepen.io/craigbuckler/full/yPqLXW).
