### ISSUE TITLE
unstuck?

### ISSUE THREAD

**Issue by eteled126** [craigbuckler/progressive-image.js#41]
Hi, Thank you for your very awesome work and creating magical visuals.
Once the images are loaded, I want to be able to zoom in to view them, so I used <a href="https://github.com/francoischalifour/medium-zoom" rel="noopener" target="_blank">https://github.com/francoischalifour/medium-zoom</a> with it, but the images don't pop up, they seem to be fixed in place.
Here's the code,
https://jsfiddle.net/eteled/y46wvc5L/12/
the second image pops up fine without progressive-image.js.
How can I get the image unstuck?

**Comment by lovecoding-git** [comment]
Hi @eteled126 
use class `zoom-defualt` instead ID.
And load it after progressive image is loaded.
`setTimeout(function() {mediumZoom(".zoom-default");}, 1000)`

**Comment by craigbuckler** [comment]
Thanks @eteled126.

As @lovecoding-git has explained, the problem is in your code sample rather than either library. You cannot have two HTML elements with the same ID. The solution to use a `class` instead of an ID works fine.
