### ISSUE TITLE
Load after the page load instead of scroll

### ISSUE THREAD

**Issue by jacobwilson1290** [craigbuckler/progressive-image.js#43]
Hello,

First of all thanks for the great plugin!

Currently images are loaded upon scroll only. Is there a way so that images are automatically loaded after the page load. We have many images on home page so visitors has to wait for images to load on scrolling.

Thank you.

**Comment by craigbuckler** [comment]
Thanks Jacob,

Are you saying images which are in-view after the page has loaded are not being fully shown until the user scrolls? That shouldn't happen - the script watches for page modifications and runs regardless of scrolling. My best guess: you have an unusual performance issue or JavaScript conflict. _Can you post a URL?_

Alternatively, are you saying you want all images to fully load without scrolling? This script is specifically used to lazy-load images. An image won't be loaded unless it's scrolled into view - that improves performance and saves bandwidth, processing time, battery, etc.

The browser's default behaviour is to load all images immediately whether they're viewed or not. So the fix would be ... _don't use this script!_

Thanks,
Craig

**Comment by craigbuckler** [comment]
Closed - no clarification received.
