### ISSUE TITLE
Page resize problem

### ISSUE THREAD

**Issue by serhatk12** [craigbuckler/progressive-image.js#44]
hello, when the screen size is changed, the pictures are deleted but the new ones are not loaded. The same thing is available in your demo. Mistake:

DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. at Image.<anonymous>

**Comment by craigbuckler** [comment]
I can see the error being logged but it doesn't seem to stop the script working?
Which browser are you using? Is there a specific page where you're seeing the issue?

**Comment by serhatk12** [comment]
https://codepen.io/craigbuckler/full/yPqLXW
For example, the bottom image on the page above opens in 480px, but when the screen expands and reaches 1080p, this error comes up. My browser is chrome.

**Comment by craigbuckler** [comment]
Ahh, I see! Thanks - I'll look into it.

**Comment by serhatk12** [comment]
`window.addEventListener &&
  window.addEventListener(
    "load",
    function () {
      "use strict";
      var e = document.body;
      if (
        e.getElementsByClassName &&
        e.querySelector &&
        e.classList &&
        e.getBoundingClientRect
      ) {
        var t,
          n = "replace",
          i = "preview",
          s = "reveal",
          r = document.getElementsByClassName("progressive " + n),
          o =
            window.requestAnimationFrame ||
            function (e) {
              e();
            };
        ["pageshow", "scroll", "resize"].forEach(function (e) {
          window.addEventListener(e, a, { passive: !0 });
        }),
          window.MutationObserver &&
            new MutationObserver(a).observe(e, {
              subtree: !0,
              childList: !0,
              attributes: !0
            }),
          c();
      }
      function a() {
        t =
          t ||
          setTimeout(function () {
            (t = null), c();
          }, 300);
      }
      function c() {
        r.length &&
          o(function () {
            for (var e, t, n = window.innerHeight, i = 0; i < r.length; )
              0 < (t = (e = r[i].getBoundingClientRect()).top) + e.height &&
              n > t
                ? u(r[i])
                : i++;
          });
      }
      function u(e, t) {
       
        e.classList.remove(n);
        var r = e.getAttribute("data-href") || e.href,
          a = e.querySelector("img." + i);
        if (r && a) {
          var c = new Image(),
            l = e.dataset;
          l &&
            (l.srcset && (c.srcset = l.srcset), l.sizes && (c.sizes = l.sizes)),
            (c.onload = function () {
              r === e.href &&
                ((e.style.cursor = "default"),
                e.addEventListener("click", function (e) {
                  e.preventDefault();
                }));
              var t = c.classList;
              (c.className = a.className),
                t.remove(i),
                t.add(s),
                (c.alt = a.alt || ""),
                o(function () {
                  e.insertBefore(c, a.nextSibling).addEventListener(
                    "animationend",
                    function () {
                     if(e && e.child && e.child.length>0){
                       e.removeChild(a), t.remove(s);
                     }
                      
                    }
                  );
                });
            }),
            (t = 1 + (t || 0)) < 3 &&
              (c.onerror = function () {
                setTimeout(function () {
                  u(e, t);
                }, 3e3 * t);
              }),
            (c.src = r);
        }
      }
    },
    !1
  `);``

I solved the problem.

**Comment by craigbuckler** [comment]
Perhaps you could issue a PR so I could check?

**Comment by serhatk12** [comment]
https://codepen.io/serhatk12/pen/NWgbRPa

**Comment by craigbuckler** [comment]
This has now been fixed. The issue was caused by responsive `srcset` images retriggering an `onload` event. The event is now disabled once the image has loaded.
