### ISSUE TITLE
Parent hyperlink is removed

### ISSUE THREAD

**Issue by niteshkejriwal** [craigbuckler/progressive-image.js#46]
I am using the lazy load in a code structure like below - 

`<a href="/actual-link">
    <div>
        <a href="/large-image" class="progressive replace">
            <img src="/mini-image" class="preview" loading="lazy" alt="image" />
        </a>
    </div>
</a>`

However, when the loading happens, the external a tag is not considered. Is there a way to do so?

**Comment by craigbuckler** [comment]
Your HTML is invalid - you cannot put a link inside another link. You don't need to though - the instructions provide the answer...

```html
<a href="/actual-link" data-href="/large-image" class="progressive replace">
  <img src="/mini-image" class="preview" loading="lazy" alt="image" />
</a>
```

Alternatively, the instructions also describe how to use (almost) any containing element:

```html
<a href="/actual-link">
  <figure data-href="/large-image" class="progressive replace">
    <img src="/mini-image" class="preview" loading="lazy" alt="image" />
  </figure>
</a>
```

**Comment by niteshkejriwal** [comment]
> Your HTML is invalid - you cannot put a link inside another link. You don't need to though - the instructions provide the answer...
> 
> ```
> <a href="/actual-link" data-href="/large-image" class="progressive replace">
>   <img src="/mini-image" class="preview" loading="lazy" alt="image" />
> </a>
> ```
> 
> Alternatively, the instructions also describe how to use (almost) any containing element:
> 
> ```
> <a href="/actual-link">
>   <figure data-href="/large-image" class="progressive replace">
>     <img src="/mini-image" class="preview" loading="lazy" alt="image" />
>   </figure>
> </a>
> ```

Works like a charm! Thanks a ton!
