### ISSUE TITLE
Background 

### ISSUE THREAD

**Issue by joaolcorreia** [craigbuckler/progressive-image.js#5]
Any idea how to use it in this case?

div data-slide-bg="images/header-1.jpg" class="swiper-slide"
          div class="swiper-slide-caption"></div
/div

Thanks
Joao

**Comment by craigbuckler** [comment]
Your code appears to be corrupted? Please can you correct it.

However, if you're asking whether it can be used for CSS backgrounds, it's not meant for that purpose (although you could adapt it). What you probably need is `object-fit: cover` on the `<img>` or its container - that will stretch so it covers the parent container.

**Comment by craigbuckler** [comment]
It's possible set CSS backgrounds - see the demo.html file or Codepen link for further details.
