### ISSUE TITLE
Different screen sizes doesn't load different photos

### ISSUE THREAD

**Issue by Shinseiten** [craigbuckler/progressive-image.js#8]
photobw is the photo in black and white. It should load it on smartphones but it doesn't happen. It load photo.png everytime.

```
<a href="image/photo.png"
    data-srcset="image/photobw.png 400w, image/photo.png 1200w"
    class="progressive replace">
    <img src="thumbnail.jpeg" class="preview"/>
</a>
```

**Comment by craigbuckler** [comment]
I'm guessing you closed this because you found a fix? The `href` should probably use `"image/photobw.png"` so any phone which didn't support responsive images would get the lower-resolution version.

**Comment by Shinseiten** [comment]
No, it's because srcset works funny on my device, but that's a problem of my browser and not your script, who work really well! :D
