### ISSUE TITLE
Does not work in a div with overflow-y:scroll

### ISSUE THREAD

**Issue by launay12u** [craigbuckler/progressive-image.js#9]
Hello, 
I want to use progressive loading on my web site but I find a issues : if the images are in a div with overflow-y:scroll, only the first image is load.

Version : lastest

Demo bug : https://jsfiddle.net/pcwudrmc/3338/

Thanks for the response and for this library

**Comment by craigbuckler** [comment]
progressive-image.js watches page scrolls to determine whether an image is in-view. 

You have a scrolling element within a page. The page itself isn't scrolling so it can't detect whether an image is visible. It could be adapted, but would probably be different in every situation, i.e. you could have multiple scrolling elements, sub-scrolling elements in others, etc.

**Comment by launay12u** [comment]
Thanks, I solved my problem I added the scroll listener on my div and made some change in the inView function as you said.

**Comment by isocroft** [comment]
@launay12u whenever you have the time, can you please share a little insight on the changes you made to the **InView** function. I have read the code for this project already so i can pretty much follow up quickly.

**Comment by launay12u** [comment]
Hey @isocroft,

Firstly I have create a `container` variable that contains my div, then instead of :

```
windows.scroll(scroller);
windows.resize(scroller);
```

I add the listen on my `container` :

```
container.scroll(scroller);
container.resize(scroller);
```

Finally in the `inView` function instead of get the windows height (`wH`) I get the `container` height.

**Comment by isocroft** [comment]
Thanks so much  for this.... I appreciate!
